services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'PGDATA=/data/postgres'
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres
    networks:
      - db_net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - db_net
    restart: unless-stopped
volumes:
  postgres:

networks:
  db_net:
    driver: bridge