spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: FlipperHura
  jpa:
    hibernate:
      ddl-auto: update
pdg:
  unitSize: 20
  tolerance: 5
  labelSimilarityThreshold: 0.2
  charVectorSimilarityThreshold: 0.7